all: q4 q2 q3 

q1: q1_main.c reverse.c headers.h 
	gcc -o q1 q1_main.c reverse.c  

q2: q2_main.c headers.h 
	gcc -o q2 q2_main.c 

q3: q3_main.c headers.h 
	gcc -o q3 q3_main.c 

q4: q4_main.c reverse.c headers.h 
	gcc -o q4 q4_main.c reverse.c  